### ISSUE TITLE
Background sync necessary for push notifications?

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#4]
Is background sync really necessary on Oreo for recieving push notifications on SDK updates? Or in that case, would they even be _push_ notifications by definition?

> Android Oreo removed these (except deletion), so the app has the option to use WorkManager to automatically fetch periodically in background for these changes. Every time the targetSDK value for an app is changed, the app will show a push notification.

For example, [a popular OSS app AfWall+](https://github.com/ukanth/afwall) is able to recognize whether an app has the internet permission whenever you install one, can that not be used here? One difference is that the app overall requires root, but I don't think that feature uses it.

**Comment by bernaferrari** [comment]
Yeah, it is impossible. When apps target an older sdk, or a previous version, Android provides system wide broadcasts. You can make an app that awakes on every app install or app update, but since Android Oreo this will not work anymore. Only when app is removed that things work. The only way is to use background sync,which, the user can choose to only happen on device is changing, so energy usage is really minimal.
