### ISSUE TITLE
Show non-Play Store apps

### ISSUE THREAD

**Issue by Madis0** [bernaferrari/SDKMonitor#5]
I am not quite sure why you hid all apps that are not installed from Play Store, though on the other hand, hiding system apps would make sense.

**Comment by bernaferrari** [comment]
Because the target sdk restriction is only imposed on play store and if I allow system apps the number of apps increase 3 times (and so does the time to sync). But eventually, like next month or so, I'm planning to include a toggle to allow all apps. Even the database already supports it. Should be a really small change.

**Comment by Madis0** [comment]
> Because the target sdk restriction is only imposed on play store
That makes it even more worthy, because with no restrictions the developers have even less reasons to update the target.

>if I allow system apps the number of apps increase 3 times
I don't think you should enable showing system apps by default at least, though it can be useful to see if something changed between OTA upgrades.

**Comment by Hugsoft** [comment]
let show apps which are not installed from Play Store and hide System Apps

**Comment by bernaferrari** [comment]
It is on the roadmap. Yesterday I completely redesigned the details dialog. I'll be focusing on this soon.

**Comment by Zebra67** [comment]
sir when will you add this feature

**Comment by bernaferrari** [comment]
Hopefully in the coming weeks! It is hard to maintain several apps, and I'm
currently committed on another one, but I thought about SDKMonitor a few
days ago.. So soon.

**Comment by bernaferrari** [comment]
Hey! I just implemented it (but still didn't push)!
I have, however, one question.

I added a "show system apps" toggle on Settings. When user toggles it, the app starts observing. But what happens when user toggles off, i.e., doesn't want to see system apps anymore?

I can:
1. Remove them.
2. Keep them and show them as if nothing happened (would ignore newer changes)
3. Keep them and filter them when fetching things.

So, should I:

1. Just remove the system apps that were being tracked from database without asking.
2. Ask user between removing them or keeping them there and not showing.
3. ???

What do you prefer? I would prefer to not have this dialog, but you are the users.

**Comment by Madis0** [comment]
>Keep them and filter/ignore them when fetching things. 
I'd choose this, as it seems the fastest and simplest option, no database rewriting required.

**Comment by bernaferrari** [comment]
Done! Please build the app or download the apk (on readme) and tell me if you like!
You shouldn't need to reinstall and the update should be really simple. If anything else happens, please tell me. I got some weird errors with emulator on app first install, but on my device everything has been working so far.
